// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProySGA.App.Persistencia;

namespace ProySGA.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211015033503_EntidadII")]
    partial class EntidadII
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Actividad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("asitencia")
                        .HasColumnType("bit");

                    b.Property<int?>("competenciaid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("periodoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("competenciaid");

                    b.HasIndex("periodoid");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Acudiente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("acudidoid")
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("acudidoid");

                    b.ToTable("Acudientes");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Area", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Asignatura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("areaid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gradoid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("areaid");

                    b.HasIndex("gradoid");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.AsignaturaGrupo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("asignaturaid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("docenteid")
                        .HasColumnType("int");

                    b.Property<int?>("grupoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("asignaturaid");

                    b.HasIndex("docenteid");

                    b.HasIndex("grupoid");

                    b.ToTable("AsignaturasGrupo");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Competencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("asignaturaid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("asignaturaid");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Grado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Grupo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("directorid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("directorid");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Matricula", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("creador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("estudianteid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("gradoid")
                        .HasColumnType("int");

                    b.Property<int?>("grupoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("estudianteid");

                    b.HasIndex("gradoid");

                    b.HasIndex("grupoid");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Periodo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Docente", b =>
                {
                    b.HasBaseType("ProySGA.App.Dominio.Entidades.Persona");

                    b.Property<string>("profesion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("salario")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasBaseType("ProySGA.App.Dominio.Entidades.Persona");

                    b.Property<int?>("madreid")
                        .HasColumnType("int");

                    b.Property<string>("nacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("padreid")
                        .HasColumnType("int");

                    b.HasIndex("madreid");

                    b.HasIndex("padreid");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Actividad", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Competencia", "competencia")
                        .WithMany()
                        .HasForeignKey("competenciaid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Periodo", "periodo")
                        .WithMany()
                        .HasForeignKey("periodoid");

                    b.Navigation("competencia");

                    b.Navigation("periodo");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Acudiente", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Estudiante", "acudido")
                        .WithMany()
                        .HasForeignKey("acudidoid");

                    b.Navigation("acudido");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Asignatura", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Area", "area")
                        .WithMany()
                        .HasForeignKey("areaid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Grado", "grado")
                        .WithMany()
                        .HasForeignKey("gradoid");

                    b.Navigation("area");

                    b.Navigation("grado");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.AsignaturaGrupo", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Asignatura", "asignatura")
                        .WithMany()
                        .HasForeignKey("asignaturaid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Docente", "docente")
                        .WithMany()
                        .HasForeignKey("docenteid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Grupo", "grupo")
                        .WithMany()
                        .HasForeignKey("grupoid");

                    b.Navigation("asignatura");

                    b.Navigation("docente");

                    b.Navigation("grupo");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Competencia", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.AsignaturaGrupo", "asignatura")
                        .WithMany()
                        .HasForeignKey("asignaturaid");

                    b.Navigation("asignatura");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Grupo", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Docente", "director")
                        .WithMany()
                        .HasForeignKey("directorid");

                    b.Navigation("director");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Matricula", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Estudiante", "estudiante")
                        .WithMany()
                        .HasForeignKey("estudianteid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Grado", "grado")
                        .WithMany()
                        .HasForeignKey("gradoid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Grupo", "grupo")
                        .WithMany()
                        .HasForeignKey("grupoid");

                    b.Navigation("estudiante");

                    b.Navigation("grado");

                    b.Navigation("grupo");
                });

            modelBuilder.Entity("ProySGA.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.HasOne("ProySGA.App.Dominio.Entidades.Persona", "madre")
                        .WithMany()
                        .HasForeignKey("madreid");

                    b.HasOne("ProySGA.App.Dominio.Entidades.Persona", "padre")
                        .WithMany()
                        .HasForeignKey("padreid");

                    b.Navigation("madre");

                    b.Navigation("padre");
                });
#pragma warning restore 612, 618
        }
    }
}
